
// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Jul  8 2024 22:21:54 IST (Jul  8 2024 16:51:54 UTC)

// Verification Directory fv/counter 

module counter(clk, m, rst, count);
  input clk, m, rst;
  output [7:0] count;
  wire clk, m, rst;
  wire [7:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26;
  SDFFRHQX1 \count_reg[7] (.RN (rst), .CK (clk), .D (count[7]), .SI
       (n_0), .SE (n_25), .Q (count[7]));
  DFFRHQX1 \count_reg[5] (.RN (rst), .CK (clk), .D (n_26), .Q
       (count[5]));
  SDFFRHQX1 \count_reg[6] (.RN (rst), .CK (clk), .D (count[6]), .SI
       (n_23), .SE (n_22), .Q (count[6]));
  OAI211X1 g664__2398(.A0 (count[5]), .A1 (n_19), .B0 (n_20), .C0
       (n_24), .Y (n_26));
  SDFFRHQX1 \count_reg[4] (.RN (rst), .CK (clk), .D (count[4]), .SI
       (n_14), .SE (n_16), .Q (count[4]));
  OAI22X1 g666__5107(.A0 (count[6]), .A1 (n_24), .B0 (n_23), .B1
       (n_21), .Y (n_25));
  DFFRHQX1 \count_reg[3] (.RN (rst), .CK (clk), .D (n_18), .Q
       (count[3]));
  NAND2XL g668__6260(.A (n_24), .B (n_21), .Y (n_22));
  NAND3X1 g671__4319(.A (count[5]), .B (n_19), .C (n_17), .Y (n_20));
  NAND2BX1 g674__8428(.AN (n_19), .B (count[5]), .Y (n_21));
  OAI211X1 g670__5526(.A0 (count[3]), .A1 (n_10), .B0 (n_15), .C0
       (n_11), .Y (n_18));
  OR2X1 g672__6783(.A (count[5]), .B (n_17), .Y (n_24));
  NAND2XL g675__3680(.A (n_15), .B (n_12), .Y (n_16));
  NAND2XL g678__1617(.A (n_14), .B (n_8), .Y (n_17));
  OAI211X1 g673__2802(.A0 (count[2]), .A1 (n_6), .B0 (n_9), .C0 (n_7),
       .Y (n_13));
  OR2X1 g679__1705(.A (n_14), .B (n_12), .Y (n_19));
  SDFFRHQX1 \count_reg[1] (.RN (rst), .CK (clk), .D (n_2), .SI (m), .SE
       (n_4), .Q (count[1]));
  NAND3X1 g677__5122(.A (count[3]), .B (n_10), .C (n_9), .Y (n_11));
  CLKINVX1 g680(.A (n_8), .Y (n_15));
  NOR2XL g681__8246(.A (count[3]), .B (n_9), .Y (n_8));
  NAND2BX1 g683__7098(.AN (n_10), .B (count[3]), .Y (n_12));
  NAND3BX1 g682__6131(.AN (n_5), .B (count[2]), .C (n_6), .Y (n_7));
  NAND2BX1 g684__1881(.AN (n_6), .B (count[2]), .Y (n_10));
  NAND2XL g685__5115(.A (n_1), .B (n_5), .Y (n_9));
  MXI2XL g688__7482(.A (n_3), .B (count[0]), .S0 (count[1]), .Y (n_4));
  NOR3X1 g687__4733(.A (m), .B (count[0]), .C (count[1]), .Y (n_5));
  NAND3X1 g686__6161(.A (m), .B (count[0]), .C (count[1]), .Y (n_6));
  INVXL g695(.A (m), .Y (n_2));
  INVXL g694(.A (count[7]), .Y (n_0));
  CLKINVX1 g690(.A (count[6]), .Y (n_23));
  CLKINVX1 g691(.A (count[4]), .Y (n_14));
  DFFRX1 \count_reg[2] (.RN (rst), .CK (clk), .D (n_13), .Q (count[2]),
       .QN (n_1));
  DFFRX1 \count_reg[0] (.RN (rst), .CK (clk), .D (n_3), .Q (count[0]),
       .QN (n_3));
endmodule