###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID Entuple-Client-1)
#  Generated on:      Sat Jul 13 14:24:53 2024
#  Design:            counter
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin clk true

# Clocks present at pin clk
#   clk (period 2.000ns) in timing_config CONSTRAINTS([counter_tool.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner MINDELAY -early -clock_tree clk 0.800

set_ccopt_property target_max_trans_sdc -delay_corner MINDELAY -late -clock_tree clk 0.800
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 2

# Skew group to balance non generated clock:clk in timing_config:CONSTRAINTS (sdc counter_tool.sdc)
create_ccopt_skew_group -name clk/CONSTRAINTS -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/CONSTRAINTS true
set_ccopt_property extracted_from_clock_name -skew_group clk/CONSTRAINTS clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/CONSTRAINTS CONSTRAINTS
set_ccopt_property extracted_from_delay_corners -skew_group clk/CONSTRAINTS {MINDELAY MAXDELAY}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}
